//Import Components
import {useState} from 'react'
import styles from '../styles/Home.module.css'
import Footer from '../components/Footer'
import Header from '../components/Header'
import CreateForm from '../components/CreateForm'
import Head from 'next/head'
import ReportTable from './ReportTable'


export default function CookieStandAdmin(){
    const[cookiesData, setCookiesData] = useState([]); //Array of objects where each object represent the data from the user

    function getUserInput(userInput){
        //userInput value is going to come from the child
        console.log(userInput)
        const cookieObj = {
            location: userInput,
            hourly_sales: [48, 42, 30, 24, 42, 24, 36, 42, 42, 48, 36, 42, 24, 36],
            total : 506,
          }
        setCookiesData([...cookiesData,cookieObj])
        // console.log(cookiesData.length)
        console.log(cookiesData)
      }
    return(
        <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header/>
        <main className='bg-green-200 py-10' >
          <div className='py-8 content-evenly flex justify-center '>
          <CreateForm getUserInput={getUserInput}/>
          </div>
          <div className=''>
            {/* <p className='text-sm flex justify-center'>Report Table Coming Soon ...</p> */}
            <p className='flex justify-center'>
            {/* {JSON.stringify(cookiesData)} */}
            <ReportTable cookiesData={cookiesData}/>
            </p>
            </div>
        </main>
        <Footer count={cookiesData.length}/>
      </div>
    )
}