import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useState} from 'react'

export default function Home() {
  const[cookiesData, setCookiesData] = useState([]); //Array of objects where each object represent the data from the user

  function handleUserInput(e){
    e.preventDefault();
    console.log('Form has been submitted')
    const cookieObj = {
      location: e.target.location.value,
      minCustomers: e.target.minCustomers.value,
      maxCustomers: e.target.maxCustomers.value,
      avgCookies: e.target.avgCookies.value,
    }
    setCookiesData(cookieObj)
    console.log(1111,cookiesData)
    console.log(2222,cookieObj)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className=''>
      <div className='bg-green-500 p-5'>
      <h1 className='text-2xl'>Cookie Stand Admin</h1>
      </div>
      </header>

      <main className='bg-green-200 py-10' >
        
        <div className='py-8 content-evenly flex justify-center '>
          <form className='bg-green-300 p-8' onSubmit={handleUserInput}>
            <h2 className='text-center text-2xl'>Create Cookie Stand</h2>
            <label>Location</label>
            <input type='text' className='border-solid border-2 border-green-500' name='location'></input>
            <br/>
            <div className='flex justify-evenly '>
            <label className='text-sm'>Minimum Customers per Hour</label>
            <label className='text-sm'>Maximum Customers per Hour</label>
            <label className='text-sm' >Average Cookies per Sale</label>
            </div>
            <br/>
            <input type='text' className='border-solid border-2 border-green-500' name='minCustomers'></input>
            <input type='text' className='border-solid border-2 border-green-500' name='maxCustomers'></input>
            <input type='text' className='border-solid border-2 border-green-500' name='avgCookies'></input>
            <button className='bg-green-700 py-1 px-7' >Create</button>
            
          </form>
        </div>
        <div className=''>
          <p className='text-sm flex justify-center'>Report Table Coming Soon ...</p>
          <p className='flex justify-center'>
          {JSON.stringify(cookiesData)}
          </p>
          </div>
      </main>

      <footer className='bg-green-500 p-5'>
        <p><span>&#169;</span>2021</p>
      </footer>
    </div>
  )
}
